

LAYERS = 2
HIDDEN_WIDTH = 100
EMBEDDING_WIDTH = 50
OUTPUT_WIDTH = 5
MAXIMUM_CONSECUTIVE_DECAYS = 5
TOP_PREDICTIONS = 3
PREDICTOR_EPOCHS = 100
PREDICTOR_SAMPLE_RATE = 0.5
GAUSSIAN_SAMPLE_RATE = 0.5
SEM_LAYERS = 2
SEM_WIDTH = 100

